### ISSUE TITLE
Drop Ncap support

### ISSUE THREAD

**Issue by jelu** [DNS-OARC/dsc#14]
Ncap have not seen any development for ~7 years.

@wessels your 2c?

**Comment by wessels** [comment]
I suggest you communicate with the DSC users (https://lists.dns-oarc.net/mailman/listinfo/dsc) before dropping any features.  In fact you should probably say something about the activity now taking place here so that users can follow and participate if they want to.

**Comment by jelu** [comment]
@wessels Yeah it's in the works, we need to look at the list management first.
