### ISSUE TITLE
response time statistics

### ISSUE THREAD

**Issue by klaus3000** [DNS-OARC/dsc#162]
Is it possible in DSC to correspond responses with requests? Then we could write a response-time analyzer

**Comment by jelu** [comment]
Yes it's possible if someone writes all the code that does it :) i.e. there
is no correlation done today.

It should be very possible to create a new indexer to track query/responses
and give QR-time per different labels, in buckets or something in that
direction.

Is this a feature you would like to sponsor in some way?

**Comment by klaus3000** [comment]
How much is it?

**Comment by jelu** [comment]
Need to look/plan/estimate first, will email you details later today.
