### ISSUE TITLE
Debian install instructions incomplete

### ISSUE THREAD

**Issue by rlegene** [DNS-OARC/dsc#179]
I couldn't ./configure until I had libpcap-dev

**Comment by jelu** [comment]
What install instructions are you referring to?

Because in the [README.md](https://github.com/DNS-OARC/dsc/blob/develop/README.md) it says:

Following dependencies are needed, example for Debian/Ubuntu.
```
sudo apt-get install libpcap-dev libproc-pid-file-perl
```

**Comment by rlegene** [comment]
Sorry, I missed that step and the current instructions are working.
