### ISSUE TITLE
unable to pcap thread run: nothing to capture on

### ISSUE THREAD

**Issue by shidex** [DNS-OARC/dsc#183]
hallo,

i try to run dsc but got the message, any someone help me?

thanks

**Comment by jelu** [comment]
What version of dsc are you running?
What OS and distribution are you running?
How did you run dsc?
Can you share full terminal output of the command?
Can you share you dsc.conf?

**Comment by shidex** [comment]
Hello Jelu,

my configuration is wrong, we must define interface and i'm using ubuntu so my interface is ens3. thanks for your fast response.
