### ISSUE TITLE
Missing configure script in release tarballs

### ISSUE THREAD

**Issue by danhanks** [DNS-OARC/dsc#199]
README.md says, "The source tarball from DNS-OARC comes prepared with configure:", however neither release 2.7.0 or 2.8.0 contain a configure script.

Thanks.

**Comment by jelu** [comment]
```
$ wget https://www.dns-oarc.net/files/dsc/dsc-2.8.0.tar.gz
$ tar zxvf dsc-2.8.0.tar.gz 
dsc-2.8.0/
...
dsc-2.8.0/configure
...
$ cd dsc-2.8.0/
$ ./configure --help
`configure' configures DSC 2.8.0 to adapt to many kinds of systems.

Usage: ./configure [OPTION]... [VAR=VALUE]...
...
```

Use the links in the [release notes](https://github.com/DNS-OARC/dsc/releases/tag/v2.8.0), not GitHub's generated tar-balls.
