### ISSUE TITLE
Response time indexer not working

### ISSUE THREAD

**Issue by danhanks** [DNS-OARC/dsc#200]
Not sure if I'm missing something obvious, but running into this problem when trying to enable response time statistics:
```
]# dsc -v
dsc version 2.8.0
]# grep ^response_time /etc/dsc/dsc.conf
response_time_mode log10;
response_time_max_queries 1000000;
]# dsc /etc/dsc/dsc.conf
CONFIG ERROR [line:242]: Unknown configuration option: response_time_mode
```
Looking at the code, I don't see any code added to src/parse_conf.c to parse the response_time config params.

**Comment by jelu** [comment]
Wow, sorry for this but it seems that completely slipped my mind and was missed by others. Will fix as soon as possible in the beginning of next week.

**Comment by jelu** [comment]
This should be fixed now, if you can please test the develop branch. A release will be made next week.
