### ISSUE TITLE
Prometheus exporter interface for dsc?

### ISSUE THREAD

**Issue by danhanks** [DNS-OARC/dsc#204]
Curious if there's been any interest in a Prometheus-compatible interface / exporter for dsc (see https://prometheus.io/docs/instrumenting/writing_exporters/)? I.e., having dsc optionally present a Promethus-scrapable endpoint for gathering statistics?

I'm currently writing some code to be run from cron which will process json output files from dsc, and translate the metrics into a format which the Prometheus textfile collector can use (see the 'textfile' section of https://github.com/prometheus/node_exporter). But it seems like a native exporter endpoint would be a more elegant solution.

Basic idea:
- A config file parameter that turns on the exporter endpoint.
- A config parameter that indicates which port the exporter endpoint listens on.
- dsc would have to synthesize metric names and help text from the configured indexers.
- Doing a GET on the endpoint would yield current values for all configured indexers formatted in the Prometheus exposition format.

**Comment by jelu** [comment]
dsc-datatool exists to do this, it can convert to Graphite and InfluxDB
today and can easily add more.

  https://github.com/DNS-OARC/dsc-datatool

Also check the wiki for an example how to set it up with Grafana.

  https://github.com/DNS-OARC/dsc-datatool/wiki/Setting-up-a-test-Grafana

**Comment by jelu** [comment]
Btw, if you want to write this native exporter then by all means go for it
:) we will happily accept pull requests with features like that. There is
also the option to fund this development work, read more about this at
https://www.dns-oarc.net/oarc/software Funding Development.

>

**Comment by jelu** [comment]
Moved to dsc-datatool
