### ISSUE TITLE
Debian package for the 2.8.1 release not available

### ISSUE THREAD

**Issue by captainark** [DNS-OARC/dsc#205]
Hi,

First of all, I apologize if this is not the right place to report this.

It would seem the debian package for the 2.8.1 release has not been made available on http://pkg.dns-oarc.net/debian.

Is there any plan to do so ?

Thanks!

**Comment by jelu** [comment]
Absolutely correct place and it looks like I missed to push them to the
Debian repository, they are built and ready.

Will do it ASAP, sorry!

**Comment by jelu** [comment]
Packages for Debian are now available, thanks for reporting this!
