### ISSUE TITLE
Stretch builds unavailable

### ISSUE THREAD

**Issue by thibmac** [DNS-OARC/dsc#209]
Hello,

I saw that there was no stretch repositories anymore on http://pkg.dns-oarc.net/debian/
Is there any chance you can keep maintaining stretch repositories (even Jessie, if possible) at least until the [end of life](https://wiki.debian.org/DebianReleases) of these releases (I am using dsc)?

I still have no plan on moving to Buster in the near future so it would be really appreciated if the updates were available on both Stretch and Jessie for a bit longer.

Best regards,

Thanks.

**Comment by jelu** [comment]
Our policy is to support at least current stable and as a non-profit organization we do not have the money or resources to support older distributions.

However, we can discuss a project/donation to support stretch until EOL 2020. Please email admin@dns-oarc.net if that something you want to look at.

It should be possible for Jessie also even tho it's passed it's EOL.
