### ISSUE TITLE
DSC with DNSTAP configured logging debug on syslog

### ISSUE THREAD

**Issue by jguidini** [DNS-OARC/dsc#220]
Hi!

Using DSC compiled with DNSTAP support I noted a lot of messages, queries received by DSC using DNSTAP, on syslog. Is like debug was enabled, but no.

I'm not in the last commit yet, my version is:
commit d910a84d91b60358fa3af97de46e02a7c293dd85

In DSC code, dsc/src/dnstap.c, I found:

```
 494    print_dnstap(m);
```

I commented this line, compiled again and the debug is almost gone, a can view on syslog messages like:

>Apr  1 15:37:22 dsc[9831]: client 1 read 210
Apr  1 15:37:22 dsc[9831]: client 1 pushing 0 of 210
Apr  1 15:37:22 dsc[9831]: client 1 pushed 210 of 210
Apr  1 15:37:22 dsc[9831]: client 1 pushed 210 of 210
Apr  1 15:37:22 dsc[9831]: client 1 pushed 210 of 210

I suggest a debug key on conf file, or disable this messages totally withou -d on command line.

Thanks!!

**Comment by jelu** [comment]
I'll look it over to see if I can minimize it but I still want some debug
since it's actually still work in progress.

I think you also can configure your syslog daemon to ignore debug messages.

**Comment by jguidini** [comment]
Syslog already configured!

Thanks!!
