### ISSUE TITLE
client_subnet indexer IPv6 performance issues

### ISSUE THREAD

**Issue by kdrenard** [DNS-OARC/dsc#263]
Greetings!

We are using the client_subnet indexer and were seeing significant performance issues with larger amounts of IPv6 traffic.  One specific dataset had 3.7M IPv4 queries and 3.6M IPv6 queries.  It was taking 15+ minutes to process 10 minutes of packet data.

I traced this down to the hash function used in the client_subnet hash table which is a pass-through to ```inXaddr_hash()```.  For that same dataset, I found that 85% of the client subnets resulted in the same hash, and sequential lookups though that very long list ended up calling ```inXaddr_cmp()``` almost 4B times while processing that dataset.  

Replacing the client_subnet indexer hash function with a call to ```hashendian()``` on the full 16 bytes of the ```inX_addr``` value produced a well-distributed hash table and improved performance significantly (down to just a few seconds).  Results on datasets were identical.  I also tested an alternative to the ```hashendian()``` function which summed the 4 32-bit values of the ```inX_addr```, throwing in a ```ntohl()``` on 2 of those 4 values.  My IPv6 performance results were almost as good as ```hashendian()```, but the lower cost of the hash function might be better for heavy-IPv4 datasets.

Diff for client_subnet_index.c:
```*** 132,138 ****
--- 132,143 ----
  static unsigned int
  ipnet_hashfunc(const void* key)
  {
+ #if 1
      return (hashendian(key, 16, 0));
+ #else
+     const inX_addr* a = key;
+     return inXaddr_hash(a);
+ #endif
  }
```
This has been running well for us for several days and I submit this for consideration to a future DSC release.

Thanks!

-Ken Renard

**Comment by jelu** [comment]
Thanks @kdrenard !

Can you test this branch https://github.com/jelu/dsc/tree/new-ip-hash ?

I've changed `inXaddr_hash()` (and more) and using `hashword()` for both v4 and v6 seems to work.
On a data set of 7mil v4 packets, doing all packets as one interval to maximize hash lookups it went from 605k cmp's to 138k.

Please let me know how it looks on your v6 data set!

**Comment by jelu** [comment]
Oh, I couldn't see any performance improvement on my v4 data set because it's too small, both old and new code takes ~1s so it's hard to measure.

**Comment by kdrenard** [comment]
This performs about 5% better than what I did (51 sec versus 54 sec) for 5GB pcap file with nearly 50/50 split of IPv4 and IPv6 (3.7M/3.5M v4/v6 queries).  Old inXaddr_hash() has been running for 75 minutes and is about 20% done.  I say this is a winner!

**Comment by kdrenard** [comment]
Note to testers/users that indexer output may vary a bit with the new hash function.  Items with the same count will likely be in a different order.  If you are using max-cells, the selection of cells at the lowest count value might be different than with the old hash.

**Comment by jelu** [comment]
> Note to testers/users that indexer output may vary a bit with the new hash function. Items with the same count will likely be in a different order. If you are using max-cells, the selection of cells at the lowest count value might be different than with the old hash.

Oh, this might actually be a bug. The [cmp func](https://github.com/DNS-OARC/dsc/blob/develop/src/md_array.c#L65) when sorting for `max-cells` only sorts on value, but not on label even if it has it. It could `strcmp()` on label if values are same to make the output consistent.

What do you think?

**Comment by kdrenard** [comment]
If you are using max-cells and only getting a subset of results where value=N, then the selection of which labels are included or dropped seems arbitrary to me.  To date, the ordering and subset selection has been based on the hash function.  Sorting on label isn't really important to me as it just changes which data points fall off the table with max-cells,  but it would preserve output consistency across future hash functions.
