### ISSUE TITLE
Remove hardcoded chmod from the code and use normal umask for permissions

### ISSUE THREAD

**Issue by subbink** [DNS-OARC/dsc#279]
At the moment all files written by dsc have [the 0644 permissions](https://github.com/DNS-OARC/dsc/blob/v2.13.1/src/daemon.c#L297). This makes it impossible to change the permissions based on the umask.
I would like to be able to use umask, so I don't have world readable files.

**Comment by jelu** [comment]
I will add new conf option to control output file access, changing it to use umask would break backwards compatibility.
