### ISSUE TITLE
Presenter graphic doesn't show CC for IPv6 clients

### ISSUE THREAD

**Issue by wfms** [DNS-OARC/dsc#5]
DSC's presenter portion doesn't display ISO Country Codes for IPv6 subnets that are clients of the DNS server being monitored.  Instead, there's a double ?? displayed.  This seems to be related to the use of the IP::Country module which is an old PERL module that only supports IPv4 whois lookups.

There's another implementation in CPAN similar to IP::Country, but requires upkeep of a database.  Alternatively, the portion doing the CC code lookup code be replaced by something else entirely to get the appropriate info.

**Comment by jelu** [comment]
Moved to https://github.com/DNS-OARC/dsp/issues/4
