### ISSUE TITLE
aggregation of data / depth of tree

### ISSUE THREAD

**Issue by teadur** [DNS-OARC/dsc#53]
What would be the best strategy for dsc presenter to show/aggregate dsc data if the node structure is:

some.tld - master aggregation of all nodes
some.tld.anycast1 - first anycast node
some.tld.anycast1-node1
some.tld.anycast1-node2
some.tld.anycast2 - second anycast node
some.tld.anycast2-node1
some.tld.anycast2-node2

Currently looking at configuration i can only aggregate one level not two levels like would be required in this scenario, how do people resolve issue like that today with dsc ?

**Comment by jelu** [comment]
Hi @teadur,

For what I know there is no such feature in the Presenter, please also note that the Presenter has moved to https://github.com/DNS-OARC/dsp .

You might want to ask on the [mailing-list](https://lists.dns-oarc.net/mailman/listinfo/dsc) if anyone have done it and have a script to share.

If you can't find a way then please make a feature request in the DSP repository.
