### ISSUE TITLE
Compile failure on centos

### ISSUE THREAD

**Issue by aabdnn** [DNS-OARC/dsc#55]
I've just tried to compile 2.0.0-rc.1 on centos 6 and centos 7. Both builds fail. I've attached the build logs of both to this report.

Mainly, it seems like the compile is failing because it's expecting some libpcap feature that appears not to be present in the libpcap packages of centos.

[centos6-build.txt](https://github.com/DNS-OARC/dsc/files/257147/centos6-build.txt)

[centos7-build.txt](https://github.com/DNS-OARC/dsc/files/257148/centos7-build.txt)

**Comment by jelu** [comment]
Hi Anand,

Did you do `yum install libpcap-devel` ?

If you did please sent/attach the spec file.

**Comment by aabdnn** [comment]
Hi Jerry. The spec file has:

```
BuildRequires:  libpcap-devel perl-Proc-PID-File
```

I can confirm that it is installed in the mock chroot:

```
<mock-chroot>[root@ostrich /]# ls /usr/include/pcap
bluetooth.h  bpf.h  ipnet.h  namedb.h  pcap.h  sll.h  usb.h  vlan.h
```

**Comment by jelu** [comment]
Hi Anand,

It seems that you took the tarball from GitHub and not DNS-OARC, the repository contains submodules now and they do not seem included in the tarball that GitHub generate.

Please try the tarball from DNS-OARC.

**Comment by aabdnn** [comment]
Got it. Apologies for the noise. The build appears to complete successfully now.
