### ISSUE TITLE
building dsc on solaris 11

### ISSUE THREAD

**Issue by teadur** [DNS-OARC/dsc#77]
Has anyone succefully built dsc on solaris11

make > make.out.1

pcap_layers/pcap_layers.c: In function ‘handle_ipv4’:
pcap_layers/pcap_layers.c:327:16: error: ‘IPPROTO_GRE’ undeclared (first use in this function)
pcap_layers/pcap_layers.c:327:16: note: each undeclared identifier is reported only once for each function it appears in
pcap_layers/pcap_layers.c: In function ‘handle_ipv6’:
pcap_layers/pcap_layers.c:396:16: error: ‘IPPROTO_GRE’ undeclared (first use in this function)
make: Fatal error: Command failed for target `pcap_layers/pcap_layers.o'
Current working directory /export/home/dsc/dsc-2.1.1/src
make: Fatal error: Command failed for target `all-recursive'
Current working directory /export/home/dsc/dsc-2.1.1/src
make: Fatal error: Command failed for target `all'
Current working directory /export/home/dsc/dsc-2.1.1/src
make: Fatal error: Command failed for target `all-recursive'

[dsc.zip](https://github.com/DNS-OARC/dsc/files/361417/dsc.zip)

**Comment by jelu** [comment]
I have not heard about anyone compiling it or having problems on Solaris (I guess very few uses it now days).

Try grepping after `IPPROTO_GRE` under `/usr/include` (or whole of `/usr`) to see if Solaris defines it in some other include file (I do not have any Solaris to test on).

If you find it we could try and make a patch.

**Comment by jelu** [comment]
You could also ask on the mailing list: https://lists.dns-oarc.net/mailman/listinfo/dsc .

**Comment by teadur** [comment]
/usr/include/netinet/ip_compat.h:#ifndef        IPPROTO_GRE
/usr/include/netinet/ip_compat.h:# define       IPPROTO_GRE     47      /* GRE encaps RFC 1701 */

**Comment by jelu** [comment]
Try:
```
git clone http://github.com/jelu/dsc.git
cd dsc
git submodule update --init
git checkout sol11-compat
./autogen.sh && ./configure && make
```

**Comment by teadur** [comment]
after adding 
+#include <netinet/ip_compat.h>
to pcay_layers.c i was able to compile dsc.

But running it seems still be problematic:

./dsc -df dsc.conf
adding local address x.x.x.x
adding local address ::1
setting current directory to /export/home/dsc/data
minfree_bytes 5000000
PID file is: /export/home/dsc/dsc.pid
Opening interface vnic1
Pcap_init: FD_SET 4
creating dataset qtype
creating dataset rcode
creating dataset opcode
creating dataset rcode_vs_replylen
creating dataset client_subnet
creating dataset qtype_vs_qnamelen
creating dataset qtype_vs_tld
creating dataset certain_qnames_vs_qtype
creating dataset client_subnet2
creating dataset client_addr_vs_rcode
creating dataset chaos_types_and_names
creating dataset idn_qname
creating dataset edns_version
creating dataset edns_bufsiz
creating dataset do_bit
creating dataset rd_bit
creating dataset idn_vs_tld
creating dataset ipv6_rsn_abusers
creating dataset transport_vs_qtype
creating dataset client_port_range
creating dataset direction_vs_ipproto
writing PID to /export/home/dsc/dsc.pid
Running
Bus Error (core dumped)

Sadly i cant find any core dump from running dir.

**Comment by jelu** [comment]
Did you try the branch from GitHub?

What did you add? Can only see `+#include`.

Have you tried with `ulimit -c unlimited` ?

**Comment by teadur** [comment]
Yes i used the sol11 branch from github.

diff --git a/pcap_layers.c b/pcap_layers.c
index 6f98430..cc91990 100644
--- a/pcap_layers.c
+++ b/pcap_layers.c
@@ -49,7 +49,7 @@
 #include <netinet/ip.h>
 #include <netinet/udp.h>
 #include <netinet/tcp.h>
-
+#include <netinet/ip_compat.h>

After some configuration i managed to dump the core file, im not sure if you can investigate it on non sparc hw.


[core.zip](https://github.com/DNS-OARC/dsc/files/365543/core.zip)

**Comment by jelu** [comment]
Check https://guides.github.com/features/mastering-markdown/ for how to paste code/output.

A core dump is not worth anything to me since I would need Solaris 11 and the binary you built, try getting a stack/back trace out of the core dump with any available tools.

**Comment by teadur** [comment]
pstack /var/cores/core.dsc.18724 
core '/var/cores/core.dsc.18724' of 18724:      ./dsc -df dsc.conf
 00034130 inXaddr_assign_v4 (ffbff070, 157d72, 0, 0, 0, 0) + 1c
 00025a40 pcap_ipv4_handler (157d66, 46, ffbff068, 0, 0, 0) + 8
 000245c4 handle_ipv4 (157d66, 46, ffbff068, 0, 0, 0) + 48
 00024674 handle_pcap (ffbff068, ffbff0f8, 157d54, 0, 0, 0) + 1c
 00024a58 pcap_handle_packet (0, ffbff0f8, 157d54, 58, 1da0d, fedf2a40) + 4c
 ff318098 pcap_read_bpf (157b48, 57889fb6, 24a0c, 0, 6c, 1) + 188
 000263c0 Pcap_run (0, 5d69c, 5d698, 1579b0, 0, 0) + 38c
 00028958 main     (ffbff204, ffbff20c, 5d800, 20560, 20540, fedf0180) + 588
 00023830 _start   (0, 0, 0, 0, 0, 0) + 5c

**Comment by jelu** [comment]
Hmm, might be an issue with `inX_addr.c`...

Can you verify that the binary has debug symbols ( `file dsc` not stripped ) ?

If not then try and recompile with debug symbols.

Then run again with `./dsc -dddddddf dsc.conf`, that will output the packets it's processing. Give me the output along with another `pstack`.

**Comment by teadur** [comment]
dsc:            ELF 32-bit MSB executable SPARC32PLUS Version 1, V8+ Required, dynamically linked, not stripped

Running with ./dsc -dddddddf dsc.conf doesnot output the packet it's proccessing

**Comment by jelu** [comment]
Maybe it never makes it to output the packets.

It is going to be hard to track this down without being able to replicate
it within my own environments and IETF96 starts tomorrow so my time will be
split.

**Comment by jelu** [comment]
It now builds on Solaris 11 but since that is not a supported platform I can not replicate the core dump issue.
