### ISSUE TITLE
Segfault in 2.2.0

### ISSUE THREAD

**Issue by McStork** [DNS-OARC/dsc#90]
Hello,

We encountered an issue with the latest version (2.2.0) or DSC. Hard to tell what exactly went wrong; all we know is that it crashed right after generating the first file.

The point is that we wanted to rollback to the previous version of DSC but we couldn't, since the package repository (http://pkg.dns-oarc.net/debian/pool/main/d/dsc/) only contains the latest version (2.2.0) of DSC.

May I suggest to keep all the past versions of DSC to ease a rollback after a failed upgrade.

**Comment by jelu** [comment]
Sad to hear it crashed, hope you can provide information on what happened so we can solve it.

Sure I could keep them around next time but they are deleted automatically because of how a Debian repository works, no easy way to roll back through `apt-get`.

**Comment by jelu** [comment]
I still have the old deb's, if you need them just tell me what dist you're running and how you want them. Feel free to contact me on email/jabber also (jerry@dns-oarc.net).

**Comment by jelu** [comment]
I have verified this, working on a fix.
