### ISSUE TITLE
allow network for local_address statement

### ISSUE THREAD

**Issue by klaus3000** [DNS-OARC/dsc#97]
--- Feature Request ---
Hi! 
We use plenty of IP addresses on our name servers, Thus we have around 1000 lines of:
local_address 1.1.1.1
local_address 1.1.1.2
local_address 1.1.1....
local_address 1.1.1.255
in our config. 
The capture filter is smart by using "and net 1.1.1.0/24" but adding all this local_addresses bloats the config. It would be great if we could configure a network/mask too.

Thanks
Klaus

**Comment by jelu** [comment]
You can do `local_address 1.1.1.0 24;` now.

**Comment by klaus3000** [comment]
Wow, great. Thank you.
Is it the same syntax for IPv6? e.g.:
local_address 2001:67c:1bc:: 48;

**Comment by jelu** [comment]
Yes, it should be. I only tested v4 so please test v6 and report if there
is any problems.
